Repository Masaaki618/todo_app, pull requests merged in 2023-01, with the labels that each got.

#8 #3 add: readmeに一行追加
  README.md
Labels: 環境構築

#11 #10 makeコマンドの修正
  Makefile
  README.md
Labels: リファクタリング, 環境構築

#17 #16 SlimとBootstrapの導入
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.scss
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.slim
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.html.slim
  app/views/layouts/mailer.text.erb
  app/views/layouts/mailer.text.slim
Labels: 環境構築

#20 Refactor dockerfile #18
  Dockerfile
  app/assets/javascripts/top.coffee
  app/assets/stylesheets/top.scss
  app/controllers/top_controller.rb
  app/helpers/top_helper.rb
  app/views/top/index.html.slim
  config/routes.rb
  test/controllers/top_controller_test.rb
Labels: リファクタリング, 環境構築

#23 Rubocop Airbnb の導入#19
  .rubocop.yml
  .rubocop_airbnb.yml
  Gemfile
  Gemfile.lock
  Makefile
  README.md
Labels: 環境構築

#26 Add model #25
  app/models/task.rb
  db/migrate/20230119132340_create_tasks.rb
  db/schema.rb
Labels: 優先

#29 Add GitHub actions #24
  .github/workflows/github-action.yml
Labels: 環境構築

#32 config routing #31
  app/assets/javascripts/tasks.coffee
  app/assets/stylesheets/tasks.scss
  app/controllers/tasks_controller.rb
  app/helpers/tasks_helper.rb
  app/views/tasks/edit.html.slim
  app/views/tasks/index.html.slim
  app/views/tasks/new.html.slim
  app/views/tasks/show.html.slim
  config/routes.rb
Labels: 環境構築

#40 Add edit #38
  app/controllers/tasks_controller.rb
  app/views/tasks/edit.html.slim
Labels: Rails, デザイン, 追加機能

#39 Add todo detail page #35
  app/controllers/tasks_controller.rb
  app/views/tasks/show.html.slim
  config/application.rb
  config/locales/ja.yml
Labels: Rails, デザイン, 追加機能

#42 Refactor error messages #41
  app/controllers/tasks_controller.rb
  app/views/shared/_error_messages.html.slim
  app/views/tasks/edit.html.slim
  app/views/tasks/new.html.slim
Labels: Rails, デザイン, リファクタリング

#43 タスク一覧表示機能の実装 #37
  app/controllers/tasks_controller.rb
  app/views/tasks/_task.html.slim
  app/views/tasks/index.html.slim
Labels: Rails, デザイン, 追加機能
